title: Tijmen Stor - Student and DevOps Engineer
description: >-
  Portfolio website of Tijmen Stor
author: Tijmen Stor
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Tijmen34
email: tijmen.stor@outlook.com
instagram_username: tijmen_075

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
